sudo: required
services:
  - docker 

before_install:
  - docker build -t kushiiitd/docker-react -f Dockerfile.dev .


script:
  - docker run kushiiitd/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerReact1"
  env: "DockerReact1-env"
  bucket_name: "elasticbeanstalk-us-east-2-748500484628"
  bucket_path: "DockerReact1"
  on: 
    branch: master
access_key_id:
access_key_id: $AWS_ACCESS_KEY
secret_access_key:
  secure: "$AWS_SECRET_KEY"

